# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer\filterToolWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_filterToolWindow(object):
    def setupUi(self, filterToolWindow):
        filterToolWindow.setObjectName("filterToolWindow")
        filterToolWindow.resize(933, 767)
        self.centralwidget = QtWidgets.QWidget(filterToolWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 10, 901, 721))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.filterTypeOption = QtWidgets.QComboBox(self.page)
        self.filterTypeOption.setGeometry(QtCore.QRect(20, 70, 221, 21))
        self.filterTypeOption.setObjectName("filterTypeOption")
        self.filterTypeOption.addItem("")
        self.filterTypeOption.addItem("")
        self.filterTypeOption.addItem("")
        self.filterTypeOption.addItem("")
        self.filterTypeOption.addItem("")
        self.approxTypeOption = QtWidgets.QComboBox(self.page)
        self.approxTypeOption.setGeometry(QtCore.QRect(20, 130, 221, 21))
        self.approxTypeOption.setObjectName("approxTypeOption")
        self.approxTypeOption.addItem("")
        self.approxTypeOption.addItem("")
        self.approxTypeOption.addItem("")
        self.filterTypeOptionLabel = QtWidgets.QLabel(self.page)
        self.filterTypeOptionLabel.setGeometry(QtCore.QRect(30, 50, 71, 16))
        self.filterTypeOptionLabel.setObjectName("filterTypeOptionLabel")
        self.aproxTypeOptionLabel = QtWidgets.QLabel(self.page)
        self.aproxTypeOptionLabel.setGeometry(QtCore.QRect(30, 110, 71, 16))
        self.aproxTypeOptionLabel.setObjectName("aproxTypeOptionLabel")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        filterToolWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(filterToolWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 933, 21))
        self.menubar.setObjectName("menubar")
        filterToolWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(filterToolWindow)
        self.statusbar.setObjectName("statusbar")
        filterToolWindow.setStatusBar(self.statusbar)

        self.retranslateUi(filterToolWindow)
        QtCore.QMetaObject.connectSlotsByName(filterToolWindow)

    def retranslateUi(self, filterToolWindow):
        _translate = QtCore.QCoreApplication.translate
        filterToolWindow.setWindowTitle(_translate("filterToolWindow", "MainWindow"))
        self.filterTypeOption.setItemText(0, _translate("filterToolWindow", "Low-Pass"))
        self.filterTypeOption.setItemText(1, _translate("filterToolWindow", "High-Pass"))
        self.filterTypeOption.setItemText(2, _translate("filterToolWindow", "Band-Pass"))
        self.filterTypeOption.setItemText(3, _translate("filterToolWindow", "Band-Rejection"))
        self.filterTypeOption.setItemText(4, _translate("filterToolWindow", "Group Delay"))
        self.approxTypeOption.setItemText(0, _translate("filterToolWindow", "Cauer"))
        self.approxTypeOption.setItemText(1, _translate("filterToolWindow", "Gauss"))
        self.approxTypeOption.setItemText(2, _translate("filterToolWindow", "Legendre"))
        self.filterTypeOptionLabel.setText(_translate("filterToolWindow", "Filter Type"))
        self.aproxTypeOptionLabel.setText(_translate("filterToolWindow", "Approximation"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    filterToolWindow = QtWidgets.QMainWindow()
    ui = Ui_filterToolWindow()
    ui.setupUi(filterToolWindow)
    filterToolWindow.show()
    sys.exit(app.exec_())
