# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer\bodePlotter.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_bodePlotterWindow(object):
    def setupUi(self, bodePlotterWindow):
        bodePlotterWindow.setObjectName("bodePlotterWindow")
        bodePlotterWindow.resize(970, 817)
        self.centralwidget = QtWidgets.QWidget(bodePlotterWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(40, 130, 141, 581))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.transferFunctionAction = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.transferFunctionAction.setObjectName("transferFunctionAction")
        self.verticalLayout.addWidget(self.transferFunctionAction)
        self.spiceAction = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.spiceAction.setObjectName("spiceAction")
        self.verticalLayout.addWidget(self.spiceAction)
        self.csvAction = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.csvAction.setObjectName("csvAction")
        self.verticalLayout.addWidget(self.csvAction)
        self.removePlotsAction = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.removePlotsAction.setObjectName("removePlotsAction")
        self.verticalLayout.addWidget(self.removePlotsAction)
        self.xLabelText = QtWidgets.QLabel(self.centralwidget)
        self.xLabelText.setGeometry(QtCore.QRect(10, 40, 41, 20))
        self.xLabelText.setObjectName("xLabelText")
        self.yLabelText = QtWidgets.QLabel(self.centralwidget)
        self.yLabelText.setGeometry(QtCore.QRect(10, 70, 47, 14))
        self.yLabelText.setObjectName("yLabelText")
        self.groupTextLabel = QtWidgets.QLabel(self.centralwidget)
        self.groupTextLabel.setGeometry(QtCore.QRect(470, 0, 151, 20))
        self.groupTextLabel.setObjectName("groupTextLabel")
        self.plotTablePhase = plotTablePhase(self.centralwidget)
        self.plotTablePhase.setGeometry(QtCore.QRect(280, 430, 651, 381))
        self.plotTablePhase.setObjectName("plotTablePhase")
        self.plotTableGain = plotTableGain(self.centralwidget)
        self.plotTableGain.setGeometry(QtCore.QRect(280, 20, 651, 401))
        self.plotTableGain.setObjectName("plotTableGain")
        self.xLabelInput = QtWidgets.QLineEdit(self.centralwidget)
        self.xLabelInput.setGeometry(QtCore.QRect(50, 40, 171, 21))
        self.xLabelInput.setObjectName("xLabelInput")
        self.yLabelInput = QtWidgets.QLineEdit(self.centralwidget)
        self.yLabelInput.setGeometry(QtCore.QRect(50, 70, 171, 21))
        self.yLabelInput.setObjectName("yLabelInput")
        self.phaseUpdateLabel = QtWidgets.QPushButton(self.centralwidget)
        self.phaseUpdateLabel.setGeometry(QtCore.QRect(130, 100, 51, 23))
        self.phaseUpdateLabel.setObjectName("phaseUpdateLabel")
        self.gainUpdateLabel = QtWidgets.QPushButton(self.centralwidget)
        self.gainUpdateLabel.setGeometry(QtCore.QRect(60, 100, 61, 23))
        self.gainUpdateLabel.setObjectName("gainUpdateLabel")
        bodePlotterWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(bodePlotterWindow)
        self.statusbar.setObjectName("statusbar")
        bodePlotterWindow.setStatusBar(self.statusbar)

        self.retranslateUi(bodePlotterWindow)
        QtCore.QMetaObject.connectSlotsByName(bodePlotterWindow)

    def retranslateUi(self, bodePlotterWindow):
        _translate = QtCore.QCoreApplication.translate
        bodePlotterWindow.setWindowTitle(_translate("bodePlotterWindow", "MainWindow"))
        self.transferFunctionAction.setText(_translate("bodePlotterWindow", "H(S)"))
        self.spiceAction.setText(_translate("bodePlotterWindow", "SPICE"))
        self.csvAction.setText(_translate("bodePlotterWindow", "Medición"))
        self.removePlotsAction.setText(_translate("bodePlotterWindow", "Borrar Gráficos"))
        self.xLabelText.setText(_translate("bodePlotterWindow", "X LABEL"))
        self.yLabelText.setText(_translate("bodePlotterWindow", "Y LABEL"))
        self.groupTextLabel.setText(_translate("bodePlotterWindow", "Plot Tool - Grupo 6"))
        self.phaseUpdateLabel.setText(_translate("bodePlotterWindow", "Fase"))
        self.gainUpdateLabel.setText(_translate("bodePlotterWindow", "Magnitud"))
from src.ui.plottablegain import plotTableGain
from src.ui.plottablephase import plotTablePhase


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    bodePlotterWindow = QtWidgets.QMainWindow()
    ui = Ui_bodePlotterWindow()
    ui.setupUi(bodePlotterWindow)
    bodePlotterWindow.show()
    sys.exit(app.exec_())
