# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer\bodePlotter.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow


class Ui_bodePlotterWindow(object):
    def setupUi(self, bodePlotterWindow):
        bodePlotterWindow.setObjectName("bodePlotterWindow")
        bodePlotterWindow.resize(574, 463)
        self.centralwidget = QtWidgets.QWidget(bodePlotterWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(50, 130, 161, 211))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.transferFunctionAction = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.transferFunctionAction.setObjectName("transferFunctionAction")
        self.verticalLayout.addWidget(self.transferFunctionAction)
        self.spiceAction = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.spiceAction.setObjectName("spiceAction")
        self.verticalLayout.addWidget(self.spiceAction)
        self.csvAction = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.csvAction.setObjectName("csvAction")
        self.verticalLayout.addWidget(self.csvAction)
        self.removePlotsAction = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.removePlotsAction.setObjectName("removePlotsAction")
        self.verticalLayout.addWidget(self.removePlotsAction)
        self.xLabelText = QtWidgets.QLabel(self.centralwidget)
        self.xLabelText.setGeometry(QtCore.QRect(36, 40, 41, 20))
        self.xLabelText.setObjectName("xLabelText")
        self.yLabelText = QtWidgets.QLabel(self.centralwidget)
        self.yLabelText.setGeometry(QtCore.QRect(40, 70, 47, 14))
        self.yLabelText.setObjectName("yLabelText")
        self.xLabetTextInput = QtWidgets.QTextEdit(self.centralwidget)
        self.xLabetTextInput.setGeometry(QtCore.QRect(100, 40, 141, 21))
        self.xLabetTextInput.setObjectName("xLabetTextInput")
        self.yLabelTextInput = QtWidgets.QTextEdit(self.centralwidget)
        self.yLabelTextInput.setGeometry(QtCore.QRect(100, 70, 141, 21))
        self.yLabelTextInput.setObjectName("yLabelTextInput")
        self.groupTextLabel = QtWidgets.QLabel(self.centralwidget)
        self.groupTextLabel.setGeometry(QtCore.QRect(350, 20, 151, 20))
        self.groupTextLabel.setObjectName("groupTextLabel")
        bodePlotterWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(bodePlotterWindow)
        self.statusbar.setObjectName("statusbar")
        bodePlotterWindow.setStatusBar(self.statusbar)

        self.retranslateUi(bodePlotterWindow)
        QtCore.QMetaObject.connectSlotsByName(bodePlotterWindow)

    def retranslateUi(self, bodePlotterWindow):
        _translate = QtCore.QCoreApplication.translate
        bodePlotterWindow.setWindowTitle(_translate("bodePlotterWindow", "MainWindow"))
        self.transferFunctionAction.setText(_translate("bodePlotterWindow", "H(S)"))
        self.spiceAction.setText(_translate("bodePlotterWindow", "SPICE"))
        self.csvAction.setText(_translate("bodePlotterWindow", "Medición"))
        self.removePlotsAction.setText(_translate("bodePlotterWindow", "Borrar Gráficos"))
        self.xLabelText.setText(_translate("bodePlotterWindow", "X LABEL"))
        self.yLabelText.setText(_translate("bodePlotterWindow", "Y LABEL"))
        self.groupTextLabel.setText(_translate("bodePlotterWindow", "Plot Tool - Grupo 6"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    bodePlotterWindow = QtWidgets.QMainWindow()
    ui = Ui_bodePlotterWindow()
    ui.setupUi(bodePlotterWindow)
    bodePlotterWindow.show()
    sys.exit(app.exec_())
