# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer\csvPopUp.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CSVInput(object):
    def setupUi(self, CSVInput):
        CSVInput.setObjectName("CSVInput")
        CSVInput.resize(400, 224)
        self.label_3 = QtWidgets.QLabel(CSVInput)
        self.label_3.setGeometry(QtCore.QRect(40, 30, 341, 21))
        self.label_3.setObjectName("label_3")

        self.retranslateUi(CSVInput)
        QtCore.QMetaObject.connectSlotsByName(CSVInput)

    def retranslateUi(self, CSVInput):
        _translate = QtCore.QCoreApplication.translate
        CSVInput.setWindowTitle(_translate("CSVInput", "Dialog"))
        self.label_3.setText(_translate("CSVInput", "Seleccione el archivo .CSV que desea graficar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CSVInput = QtWidgets.QDialog()
    ui = Ui_CSVInput()
    ui.setupUi(CSVInput)
    CSVInput.show()
    sys.exit(app.exec_())
