# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer\LTSpicePopUp.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LTSpiceInput(object):
    def setupUi(self, LTSpiceInput):
        LTSpiceInput.setObjectName("LTSpiceInput")
        LTSpiceInput.resize(400, 224)
        self.label_3 = QtWidgets.QLabel(LTSpiceInput)
        self.label_3.setGeometry(QtCore.QRect(30, 30, 341, 21))
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(LTSpiceInput)
        self.pushButton.setGeometry(QtCore.QRect(150, 120, 75, 23))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(LTSpiceInput)
        QtCore.QMetaObject.connectSlotsByName(LTSpiceInput)

    def retranslateUi(self, LTSpiceInput):
        _translate = QtCore.QCoreApplication.translate
        LTSpiceInput.setWindowTitle(_translate("LTSpiceInput", "Dialog"))
        self.label_3.setText(_translate("LTSpiceInput", "Seleccione el archivo de LTSpice que desea graficar"))
        self.pushButton.setText(_translate("LTSpiceInput", "PushButton"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LTSpiceInput = QtWidgets.QDialog()
    ui = Ui_LTSpiceInput()
    ui.setupUi(LTSpiceInput)
    LTSpiceInput.show()
    sys.exit(app.exec_())
