# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer\transferFunctionPopUp.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_transferFunctionInput(object):
    def setupUi(self, transferFunctionInput):
        transferFunctionInput.setObjectName("transferFunctionInput")
        transferFunctionInput.resize(400, 224)
        self.transferNumeratorLabel = QtWidgets.QLabel(transferFunctionInput)
        self.transferNumeratorLabel.setGeometry(QtCore.QRect(30, 70, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.transferNumeratorLabel.setFont(font)
        self.transferNumeratorLabel.setObjectName("transferNumeratorLabel")
        self.transferDenominatorLabel = QtWidgets.QLabel(transferFunctionInput)
        self.transferDenominatorLabel.setGeometry(QtCore.QRect(30, 110, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.transferDenominatorLabel.setFont(font)
        self.transferDenominatorLabel.setObjectName("transferDenominatorLabel")
        self.label_3 = QtWidgets.QLabel(transferFunctionInput)
        self.label_3.setGeometry(QtCore.QRect(40, 30, 341, 21))
        self.label_3.setObjectName("label_3")
        self.trasnferNumeratorInput = QtWidgets.QLineEdit(transferFunctionInput)
        self.trasnferNumeratorInput.setGeometry(QtCore.QRect(190, 70, 171, 31))
        self.trasnferNumeratorInput.setObjectName("trasnferNumeratorInput")
        self.transferDenominatorInput = QtWidgets.QLineEdit(transferFunctionInput)
        self.transferDenominatorInput.setGeometry(QtCore.QRect(190, 120, 171, 31))
        self.transferDenominatorInput.setObjectName("transferDenominatorInput")
        self.inputOkAction = QtWidgets.QPushButton(transferFunctionInput)
        self.inputOkAction.setGeometry(QtCore.QRect(150, 180, 75, 23))
        self.inputOkAction.setObjectName("inputOkAction")

        self.retranslateUi(transferFunctionInput)
        QtCore.QMetaObject.connectSlotsByName(transferFunctionInput)

    def retranslateUi(self, transferFunctionInput):
        _translate = QtCore.QCoreApplication.translate
        transferFunctionInput.setWindowTitle(_translate("transferFunctionInput", "Dialog"))
        self.transferNumeratorLabel.setText(_translate("transferFunctionInput", "Numerador"))
        self.transferDenominatorLabel.setText(_translate("transferFunctionInput", "Denominador"))
        self.label_3.setText(_translate("transferFunctionInput", "Ingrese los valores de los coeficientes de la función de transferencia"))
        self.inputOkAction.setText(_translate("transferFunctionInput", "Ingresar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    transferFunctionInput = QtWidgets.QDialog()
    ui = Ui_transferFunctionInput()
    ui.setupUi(transferFunctionInput)
    transferFunctionInput.show()
    sys.exit(app.exec_())
